version: "3.9"

networks:
  local-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine3.17
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www/api
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - local-network

  php:
    build:
      context: .
    container_name: ${APP_NAME}-php
    restart: always
    volumes:
      - ./src:/var/www/api
    ports:
      - "${PHP_PORT}:9000"
    command: bash -c "composer install && php-fpm"
    networks:
      - local-network

  pgsql:
    container_name: ${APP_NAME}-pgSQL
    image: postgres:13
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    networks:
      - local-network

  pgadmin:
    container_name: ${APP_NAME}-pgAdmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - local-network

